package net.ent.etnc.jurassicpark.business.commons;

public enum ErreurValidation {

    AUCUN_ANIMAL,
    AUCUN_ENCLOS,
    AUCUN_PERSONNEL,
    PERSONNEL_NON_QUALIFIE,
    PERSONNEL_NON_DISPONIBLE,
    PERSONNEL_INSUFFISANT,
    ANIMAL_NON_DISPONIBLE,
    ANIMAUX_INCOMPATIBLES,
    ENCLOS_INACTIF,
    ENCLOS_INCOMPATIBLE,
    ENCLOS_NON_VIDE,
    ENCLOS_TROP_PETIT,
    MANIPULATION_ANIMAL_MORT,
    SECURITE_INSUFFISANTE
}
